### ISSUE TITLE
A video has been deleted by YouTube

### ISSUE THREAD

**Issue by Cogito2012** [MoonBlvd/tad-IROS2019#13]
@MoonBlvd 
Thanks for your effort in this project. When I run the code `A3D_download.py` to download the video files as listed in the `A3D_urls.txt`, I found that this video  [CwLSDLEP2mU](https://www.youtube.com/watch?v=CwLSDLEP2mU) (as listed in line [201] (https://github.com/MoonBlvd/tad-IROS2019/blob/7f4e38ea6f774738154dff5d3b4cac34b46f5309/datasets/A3D_urls.txt#L201) has been removed by YouTube.

Hope you can provide it. Thanks

**Comment by MoonBlvd** [comment]
@Cogito2012  I think they have removed some of their videos for some reason. I am not sure if I have authority to share the original video file. But I checked the video for you, it is a 2mins video containing only 8 sub-videos. To help you start experiment quickly, my suggestion is to just ignore this video since A3D has ~1500 videos in total. I will contact the youtube channel, hopefully they can let me know why they decided to remove those videos.

Thank you,
Brian

**Comment by Cogito2012** [comment]
@MoonBlvd Thanks! 
Anyway, I'll try to ignore this video.
